### ISSUE TITLE
Logs: GetChanges start/duration wrong in server logs, but correct in analyzer client

### ISSUE THREAD

**Issue by bzz** [src-d/lookout#192] opened 2018-08-25 07:03 UTC
### Steps to reproduce:

```
git clone https://github.com/bzz/lookout-gometalint-analyzer.git

./dummy serve --files
./lookout push --log-level=debug \
  --git-dir="$(pwd)/lookout-gometalint-analyzer" \
  --from="a044e568d6b3bd6bf5ecf49fdd8c170de53fcb73" \
  --to="86466b69281ca6bdcbc55413014ddb5a5ac4ce50" \
  "ipv4://localhost:10302"
```
 
### Current outcome

**dummy**

```
[2018-08-25T08:25:08.865845377+02:00]  INFO unary server call started app=dummy grpc.method=NotifyReviewEvent grpc.service=pb.Analyzer span.kind=server
[2018-08-25T08:25:08.865958498+02:00]  INFO streaming client call started app=dummy grpc.method=GetChanges grpc.service=pb.Data span.kind=client
[2018-08-25T08:27:01.75096783+02:00]  INFO streaming client call finished app=dummy duration=1m52.883637794s grpc.code=OK grpc.method=GetChanges grpc.service=pb.Data grpc.start_time=2018-08-25T08:25:08+02:00 span.kind=client
```

**lookout**
```
[2018-08-25T08:25:08.865371384+02:00]  INFO unary client call started app=lookout grpc.method=NotifyReviewEvent grpc.service=pb.Analyzer source=grpchelper/logger.go:19 span.kind=client
[2018-08-25T08:27:01.751310681+02:00]  INFO streaming server call started app=lookout grpc.method=GetChanges grpc.service=pb.Data source=grpchelper/logger.go:19 span.kind=server
[2018-08-25T08:27:01.751839142+02:00]  INFO streaming server call finished app=lookout duration=537.99µs grpc.method=GetChanges grpc.service=pb.Data grpc.start_time=2018-08-25T08:27:01+02:00 source=grpchelper/logger.go:19 span.kind=server 
```

### Expected outcome
Client and server of DataService both report same duration of `GetChanges` call in logs

--------

Current behavior complicates debugging: it's 2 min but instead server reports `duration=537.99µs` :/
Client report is correct `duration=1m52.883637794s` but it does not have any breakdown of where this time was spent

It also brings confusing UX: user of SDK just sees that analyzer has been notified, and then no feedback for 2 min.

**Comment by smacker** [comment] 2018-09-07 14:33
Most probably steps aren't completely right because in description I see `GetChanges` but the commands would produce call to `GetFiles`.

Anyway with files:
```
[2018-09-07T16:25:22.85648559+02:00]  INFO streaming server call started app=lookout-sdk grpc.method=GetFiles grpc.service=pb.Data source=grpchelper/logger.go:19 span.kind=server system=grpc
[2018-09-07T16:25:23.130002084+02:00]  INFO streaming server call finished app=lookout-sdk duration=273.529426ms grpc.code=OK grpc.method=GetFiles grpc.service=pb.Data grpc.start_time=2018-09-07T16:25:22+02:00 source=grpchelper/logger.go:19 span.kind=server system=grpc
```

With changes:
```
[2018-09-07T16:32:07.265994527+02:00]  INFO streaming server call finished app=lookout-sdk duration=17.136147ms grpc.code=OK grpc.method=GetChanges grpc.service=pb.Data grpc.start_time=2018-09-07T16:32:07+02:00 source=grpchelper/logger.go:19 span.kind=server system=grpc
[2018-09-07T16:32:07.26664882+02:00]  INFO streaming client call finished app=lookout-sdk duration=992.470075ms grpc.code=OK grpc.method=NotifyReviewEvent grpc.service=pb.Analyzer grpc.start_time=2018-09-07T16:32:06+02:00 source=grpchelper/logger.go:19 span.kind=client system=grpc
```

All numbers are correct.

Can't reproduce.

**Comment by carlosms** [comment] 2019-01-09 18:23
Let's close this one, @bzz?

**Closed** 2019-01-10 17:43 UTC
Labels: bug
