### ISSUE TITLE
Unit test failure on master

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout#519] opened 2019-02-08 19:14 UTC
Travis has failed on master for this test.
https://travis-ci.org/src-d/lookout/jobs/490687581

```
    --- FAIL: TestServerCancel/get-changes-size-6-cancel-at-0 (0.00s)
        require.go:248: 
            	Error Trace:	data_test.go:177
            	Error:      	An error is expected but got nil.
            	Test:       	TestServerCancel/get-changes-size-6-cancel-at-0
```

A restart solved the issue, but we need to find out the reason.

**Comment by se7entyse7en** [comment] 2019-02-12 19:34
This seems to be really difficult to reproduce 😕. I've added some logging message to debug and I've done this so far:

```
while ! {grep "FAIL" out.txt > /dev/null}; do go test -v -run TestServerCancel/get-changes-size-6-cancel-at-0 >> out.txt; done
```

But no luck. I also tried by running all the `TestServerCancel`, but still no luck. And by studying the code I cannot understand how that is happening. The only thing that I'm thinking is that for some reason the grpc client stream "realizes" about the context cancellation not immediately in some particular cases. This permit the client to still read through `Recv`. But it's really a guess.

**Comment by se7entyse7en** [comment] 2019-02-12 19:38
Anyway from the log messages that I've added to investigate this issue, I'm sure that sometimes the server tries to `Send` something into the stream even if the client already `Recv`ed the `context cancelled` error. It's actually rare, but when it happens on the server here are the two possible errors that I encountered:
- `rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called`
- `rpc error: code = Unavailable desc = transport is closing`

I'm wondering wheter there could be some particular condition in which the server writes to the stream just before it realizes that the context has been cancelled. But I don't have deep knowledge of the internals.

**Comment by se7entyse7en** [comment] 2019-02-13 16:06
Putting this back to `TODO` as I was not able to reproduce it 😞.

**Comment by se7entyse7en** [comment] 2019-02-22 20:01
Even if maybe it was a bit obvious, the problem is not only in that particular test. I had the same problem for `TestServerCancel/get-changes-size-9-cancel-at-2`.

**Comment by carlosms** [comment] 2019-02-25 13:30
Another example here, `get-files-size-4-cancel-at-3`: https://travis-ci.org/src-d/lookout/jobs/497784692#L849

**Comment by se7entyse7en** [comment] 2019-04-04 15:49
I wanted to try to run the tests with the `-race` flag, but everything seemed to be ok, I don't actually know what to do except for what I already tried. Putting back to `To Do`.

**Closed** 2019-04-08 11:47 UTC
Labels: bug
