### ISSUE TITLE
Publish lookoutd binary in releases

### ISSUE THREAD

**Issue by smola** [src-d/lookout#300] opened 2018-09-27 09:14 UTC
It seems only lookout-sdk bonary is present in releases. lookoutd should be published too.

**Comment by carlosms** [comment] 2018-09-27 09:56
Closing as duplicate of https://github.com/src-d/lookout/issues/270.
We have just merged that one, next release (today?) should contain the binaries.

Thanks!

**Closed by carlosms** 2018-09-27 09:56 UTC
Labels: enhancement
