### ISSUE TITLE
Review event chokes on git submodules

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/lookout#144] opened 2018-08-16 09:33 UTC
Looks like something goes wrong if the commit includes a git submodule update. Steps to reproduce:

1. Checkout the latest master of src-d/style-analyzer
2. `./lookout review -v ipv4://localhost:2000 --from c99dcdff172f1cb5505603a45d054998cb4dd606 --to 3a9d78bdd1139c929903885ecb8f811931b8aa70` (this includes the submodule update)

You get

```
[2018-08-16T11:32:01.355326446+02:00]  INFO streaming server call finished app=lookout duration=670.461043ms error=file not found grpc.code=Unknown grpc.method=GetChanges grpc.service=pb.Data grpc.start_time=2018-08-16T11:32:00+02:00 source=grpchelper/logger.go:19 span.kind=server system=grpc
[2018-08-16T11:32:01.364247864+02:00]  INFO streaming client call finished app=lookout duration=734.359432ms error=rpc error: code = Internal desc = <class 'grpc._channel._Rendezvous'>: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "file not found"
	debug_error_string = "{"created":"@1534411921.355470703","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1083,"grpc_message":"file not found","grpc_status":2}"
> grpc.code=Internal grpc.method=NotifyReviewEvent grpc.service=pb.Analyzer grpc.start_time=2018-08-16T11:32:00+02:00 source=grpchelper/logger.go:19 span.kind=client system=grpc
[2018-08-16T11:32:01.36433733+02:00] ERROR analysis failed analyzer=test-analyzes app=lookout error=rpc error: code = Internal desc = <class 'grpc._channel._Rendezvous'>: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "file not found"
	debug_error_string = "{"created":"@1534411921.355470703","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1083,"grpc_message":"file not found","grpc_status":2}"
> head=3a9d78bdd1139c929903885ecb8f811931b8aa70 provider= repository=file:///home/vadim/Projects/style-analyzer source=server/server.go:256
[2018-08-16T11:32:01.364385434+02:00]  INFO status: success app=lookout source=lookout/serve.go:351
```

**Comment by bzz** [comment] 2018-08-16 11:13
Thank you for reproducible example! Looking into it

**Comment by bzz** [comment] 2018-08-16 12:29
I belive we have to decide, what would be the expected behavior in case of changes to sub-modules, like in your example https://github.com/src-d/style-analyzer/compare/c99dcdff172f1cb5505603a45d054998cb4dd606...src-d:3a9d78

In any case, it should not be a "file not found" error, which happens now because go-git `object.Tree.File("path/to/submodule")` can not find an entry for sub-module.

**Comment by vmarkovtsev** [comment] 2018-08-16 12:50
I would exclude such objects completely from the review response, they are not needed.

**Comment by bzz** [comment] 2018-08-21 08:29
Closing as #150 is merged & released now

**Closed by bzz** 2018-08-21 08:29 UTC
Labels: bug
